name: Merge Example

on:
  push:
    branches:
      - main
    paths:
      - typescript-project/**
  workflow_dispatch:  # This is a manual trigger

jobs:
  merge:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./typescript-project  # Ensure this path is correct

    steps:
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: 'typescript-project/yarn.lock'
          

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile  # Ensure yarn.lock exists in the working directory

      # Run linting
      - name: Run linting
        run: yarn lint

      # Build project
      - name: Build project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test
      
      - run: git config user.email "emimo56@gmail.com"
      - run: git config user.name "@github-ci"
      - run: yarn version --patch --message "Bump version to %s"

      - run: git push

      - run: git push --follow-tags
